@host = http://localhost:5076
@DataUrl = https://flapotest.blob.core.windows.net/test/ProductData.json

### All results combined
GET {{host}}/api/product/all?url={{DataUrl}}
Accept: application/json

### Most expensive and cheapest beer per litre
GET {{host}}/api/product/most-expensive-cheapest?url={{DataUrl}}
Accept: application/json

### Beers costing exactly €17.99 (sorted by price/litre)
GET {{host}}/api/product/beers-at-1799?url={{DataUrl}}
Accept: application/json

### Product with most bottles
GET {{host}}/api/product/most-bottles?url={{DataUrl}}
Accept: application/json

### Fetch source data
GET https://flapotest.blob.core.windows.net/test/ProductData.json
Accept: application/json

###